---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import vaiables
      include_vars: vars/output_vars

    - name: import vaiables
      include_vars: vars/vpc_setup

    - name: creat key pair
      ec2_key:
        name: bastion_key
        region: "{{region}}"
        state: "{{state}}"
      register: key_out

    - name: save private key
      copy:
        content: "{{key_out.key.private_key}}"
        dest: ./bastion-key.pem
        mode: 0600
      when: key_out.changed

    - name: create security group
      ec2_group:
        name: bastion_SG
        description: sg with rule descriptions
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
      register: group_out

    - name: create bastion host
      ec2:
        key_name: bastion_key
        instance_type: t2.micro
        region: "{{region}}"
        image: "{{bastion_ami}}"
        vpc_subnet_id: "{{pubsub1id}}"
        group_id: "{{group_out.group_id}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: bastion_host
          project: vprofile
          owner: devops team
        exact_count: 1
        count_tag:
          Name: bastion_host
          project: vprofile
          owner: devops team
      register: bastionhost_out

    - name: save group id
      blockinfile:
        path: vars/output_vars
        backup: no
        block:
          bastionSGid: {{group_out.group_id}}

