---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import vpc variable
      include_vars: vars/vpc_setup

    - name: create vprofile vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        tenancy: default
        dns_support: yes
        dns_hostnames: yes
      register: vpc_out

    - name: creating public subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        cidr: "{{pubsub1Cidr}}"
        map_public: yes
        az: "{{zone1}}"
        tags:
          Name: pubsub1
      register: pubsub1_out

