---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import the out_put variables
      include_vars: vars/output_vars

    - name: import the stack vars
      include_vars: vars/vpro-stack-var

    - name: create key-pair for all instances
      ec2_key:
        name: vpro-stack-key
        region: "{{region}}"
        state: present
      register: stack_key

    - name: saving the private key
      copy:
        content: "{{stack_key.key.private_key}}"
        dest: ./vpro-stack-key.pem
        mode: 0600
      when: stack_key.changed

    - name: load balancer security group
      ec2_group:
        name: vproELB_SG
        description: SG with relus defined
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELB_SG_out

    - name: create SG for vprofile stack
      ec2_group:
        name: vpro_stack_SG
        description: SG for vprofilr stack
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vproELB_SG_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{bastionSGid}}"
      register: vpro_stack_sg_out


