---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: import vpc variable
      include_vars: vars/vpc_setup

    - name: create vprofile vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        tenancy: default
        dns_support: yes
        dns_hostnames: yes
        state: "{{state}}"
      register: vpc_out

    - name: creating public subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        cidr: "{{pubsub1Cidr}}"
        map_public: yes
        az: "{{zone1}}"
        tags:
          Name: pubsub1
      register: pubsub1_out

    - name: creating public subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        cidr: "{{pubsub2Cidr}}"
        map_public: yes
        az: "{{zone2}}"
        tags:
          Name: pubsub2
      register: pubsub2_out

    - name: creating public subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        cidr: "{{pubsub3Cidr}}"
        map_public: yes
        az: "{{zone3}}"
        tags:
          Name: pubsub3
      register: pubsub3_out

    - name: creating private subnet1
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        cidr: "{{prisub1Cidr}}"
        map_public: no
        az: "{{zone1}}"
        tags:
          Name: prisub1
      register: prisub1_out

    - name: creating private subnet2
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        cidr: "{{prisub2Cidr}}"
        map_public: no
        az: "{{zone2}}"
        tags:
          Name: prisub2
      register: prisub2_out

    - name: creating private subnet3
      ec2_vpc_subnet:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        cidr: "{{prisub3Cidr}}"
        map_public: no
        az: "{{zone3}}"
        tags:
          Name: prisub3
      register: prisub3_out

    - name: creating internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpc_out.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: vprofile-vpc-IGW
        state: "{{state}}"
      register: igw_out






